---
name: Build and test emasser

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
          fetch-depth: 0
      - name: Fetch all tags for versioning 
        run: git fetch origin +refs/tags/*:refs/tags/*
      - name: Setup Ruby 2.7
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
      - name: Install bundler and git-lite-version-bump
        run: gem install bundler git-lite-version-bump
      - name: Run bundle install
        run: bundle install
      - name: Generate mapping objects
        run: bundle exec rake generate_mapping_objects
      - name: Run rubocop
        run: bundle exec rubocop
      - name: Run bundle-audit
        run: bundle-audit check --update
      - name: Build swagger_client gem
        run: gem build swagger_client.gemspec
      - name: Upload swagger_client gem
        uses: actions/upload-artifact@v2
        with:
          name: swagger_client_gem
          path: swagger_client-*.gem

  test-gem:
    needs: build
    strategy:
      fail-fast: false
      matrix: 
       platform: [ ubuntu-latest, macos-latest, windows-latest ]
       ruby: [ 2.5, 2.6, 2.7 ]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Setup Ruby ${{matrix.ruby}}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{matrix.ruby}}
      - uses: actions/checkout@v2
        with:
          lfs: true
          fetch-depth: 0
      - name: Download swagger_client gem
        uses: actions/download-artifact@v2
        with:
          name: swagger_client_gem
      - name: Install swagger_client gem
        run: gem install swagger_client-*.gem


  test:
    strategy:
      fail-fast: false
      matrix: 
       platform: [ ubuntu-latest, macos-latest, windows-latest ]
       ruby: [ 2.5, 2.6, 2.7 ]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Setup Ruby ${{matrix.ruby}}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{matrix.ruby}}
      - uses: actions/checkout@v2
        with:
          lfs: true
          fetch-depth: 0
      - name: Install bundler and git-lite-version-bump
        run: gem install bundler git-lite-version-bump
      - name: Run bundle install
        run: bundle install
      - name: Generate mapping objects
        run: bundle exec rake generate_mapping_objects
      - name: Run rake test
        run: bundle exec rake test
        