name: Test emasser CLI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix: 
       platform: [ ubuntu-latest, macos-latest, windows-latest ]
       ruby-version: ['2.6', '2.7']
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Setup Ruby ${{matrix.ruby}}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
      # - uses: actions/checkout@v2    
      #   with:
      #     lfs: true
      #     fetch-depth: 0
      - uses: actions/checkout@v2
      - name: Run cli tests
        run: |
          bundle install
          bundle info swagger_client
          # rspec spec --format documentation
          rspec spec/test_emasser_cli_spec.rb --format documentation
          rspec spec/test_get_cli_spec.rb --format documentation
          rspec spec/test_put_cli_spec.rb --format documentation
          rspec spec/test_post_cli_spec.rb --format documentation
