name: Test emasser CLI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix: 
       platform: [ ubuntu-latest, macos-latest, windows-latest ]
       ruby-version: ['2.6', '2.7']
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Setup Ruby ${{matrix.ruby}}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
      - uses: actions/checkout@v2
      - name: Testing on Windows for Ruby ${{ matrix.ruby }}
        if: ${{ matrix.platform }} == 'windows-latest'
        uses: wei/curl@v1
        run: |
          bundle install
          bundle info swagger_client
          rspec spec --format documentation
      - name: Testing on ${{ matrix.platform }} for Ruby ${{ matrix.ruby }}
        run: |
          bundle install
          bundle info swagger_client
          rspec spec --format documentation
